### ISSUE TITLE
Requirements Issues

### ISSUE THREAD

**Issue by JSluo888** [hms-dbmi/CHIEF#16]
Hi,

I am wondering if it would be possible to update the requirements.txt file? Currently when I try to install those packages I get a lot of version conflicts, and some packages do not even exist using pip install. 

Could you please tell me the minimal packages I would need in order to simply extract features from WSI? No need to finetune for now. 

Tysm!

**Comment by JSluo888** [comment]
Just to add that for some reasons I cannot use docker, so it would be great if you can illustrate how to set up the environment in a conda environment.

**Comment by Xiyue-Wang** [comment]
Hi, If you only want to extract features, this has the minimum required congfie file(https://drive.google.com/file/d/1bFJ-4aMuwOaz8rh473wY77dxUFy7S7vF/view?usp=sharing)

conda env create -f CHIEF_minimal.yaml
conda activate CHIEF_minimal

Finally, don't forget to follow pip install with a slight modification of the timm in the readme
