### ISSUE TITLE
How to Resolve FileNotFoundError for TCGA File

### ISSUE THREAD

**Issue by Kevin201610** [hms-dbmi/CHIEF#17]
I'm encountering an error while running the project. I came across a FileNotFoundError indicating the program couldn't locate the file TCGA-US-A774-01Z-00-DX1.522FF138-153F-488A-BBBC-5EA68EFD80C7.pt within the ./feature/tcga directory.

To troubleshoot this, it would be helpful to understand if there are specific instructions for downloading or generating this file.  Any guidance you can provide on how to address this missing file error would be greatly appreciated!

**Comment by Xiyue-Wang** [comment]
Hi, you can use dokcer.

**Comment by Dadatata-JZ** [comment]
Hi Kevin, 

It was a toy (demonstration) feature file. You should be able to generate it and replace it using the extracted features for other slide.
