### ISSUE TITLE
Cancer cell detection tasks

### ISSUE THREAD

**Issue by FabianHoerst** [hms-dbmi/CHIEF#22]
Hello, 

thank you for your outstanding work and congrats for the acceptance! I have a question regarding the "Cancer cell detection task". Have you included healthy tissue images inside your work to see the performance when non cancer slides are within the dataset? Is your model able to distinguish between healthy and malignant slides?

Thanks in advance!

**Comment by Xiyue-Wang** [comment]
Yes, It can distinguish between healthy and malignant slides!
