### ISSUE TITLE
Accessing Error CHIEF Model Weights via Docker

### ISSUE THREAD

**Issue by GrowUpLikeSophia** [hms-dbmi/CHIEF#26]
Dear Author,

I hope this message finds you well. I encountered an error while trying to access the CHIEF model weights using Docker. 

`bash-4.2$ docker pull chiefcontainer/chief:v1.11`

`permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=chiefcontainer%2Fchief&tag=v1.11": dial unix /var/run/docker.sock: connect: permission denied`

`bash-4.2$ docker run --rm -it --entrypoint /bin/bash chiefcontainer/chief:v1.11`

`docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.`

This error may be related to network restrictions on our servers in China. Could you kindly provide an alternative method to download and use the model weights locally? I would be truly grateful for your assistance.

Best regards.

**Comment by Dadatata-JZ** [comment]
@GrowUpLikeSophia 
Sophia, 

Feel free to use g-drive to download our weights. Cheers

https://drive.google.com/drive/u/1/folders/1uRv9A1HuTW5m_pJoyMzdN31bE1i-tDaV

**Comment by GrowUpLikeSophia** [comment]
XIEXIE！！！！THANKS！！！😀
