### ISSUE TITLE
Details of PT files

### ISSUE THREAD

**Issue by itoi9350** [hms-dbmi/CHIEF#36]
For a file like TCGA-LN-A8I1-01Z-00-DX1.F2C4FBC3-1FFA-45E9-9483-C3F1B2B7EF2D.pt, I noticed there are two versions: one is 6.76 MB, and the other is 2.73 kB. Could you explain the reason for this difference?

**Comment by Dadatata-JZ** [comment]
@itoi9350 Hi, Try to load them and peek inside. The one in 2.73KB sounds like debris—not even enough for coordinates. Let me know if you meet any issues.
